# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-02c295b01d50c9q3r:
resource "aws_internet_gateway" "igw-02c295b01d50c9q3r" {
  tags = {
    "Name" = "igw-eks-cluster"
  }
  vpc_id = aws_vpc.cluster.id
}